### ISSUE TITLE
scroll probably needs to depend on exact scroll_derive version

### ISSUE THREAD

**Issue by ignatenkobrain** [m4b/scroll#22]
0.8.0 (scroll) + 0.8.1 (scroll_derive) results into failing build of goblin:
```rust
error[E0433]: failed to resolve. Could not find `export` in `scroll`
   --> src/elf/program_header.rs:340:40
    |
340 |     #[cfg_attr(feature = "std", derive(Pread, Pwrite, SizeWith))]
    |                                        ^^^^^ Could not find `export` in `scroll`
[…]
```

**Comment by philipc** [comment]
I think scroll_derive should have been bumped to 0.9 since it's not backwards compatible with earlier scroll versions.

**Comment by ignatenkobrain** [comment]
@philipc well, if I have both 0.8.1, then everything works fine, it's just been that one was 0.8.0 and another 0.8.1....

**Comment by philipc** [comment]
Sure, but if the semantic versions were correct then it wouldn't have tried to mix them.

**Comment by m4b** [comment]
I don’t even understand why it would have 0.8 and 0.8.1. Scroll reexports it’s derive version so I don’t even see how this error could happen ...?

Anyway I guess I’ll yank 0.8.1 for both and publish 0.9 for both. I prefer to have same version for both, as it’s less confusing. 

@philipc are there any more changes to these two crates do you think ?

**Comment by m4b** [comment]
@ignatenkobrain

Is the goblin build failing on git master or from crates.io?

It crates that’s serious and def need to yank scroll versions

**Comment by ignatenkobrain** [comment]
@m4b latest goblin builds fine with `scroll 0.8.1` + `scroll_derive 0.8.1`

**Comment by philipc** [comment]
@m4b I don't expect more changes.

**Comment by m4b** [comment]
this is super old and I'm not sure what we should do about this; please reopen if it happens again
